name: selectify
description: "A flexible and highly customizable Flutter library for single and multiple selections, offering functionality similar to radio and checkbox buttons."
version: 1.0.0
homepage: https://solrum.dev
repository: https://github.com/solrum/flutter/tree/master/selection

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: