name: text_input_formatter
description: "A Flutter package that provides customizable input formatting for text fields. Easily enforce specific patterns and separators, ensuring consistent and user-friendly text input experiences. Ideal for formatting dates, numbers, or any other structured input, this package enhances your app's data entry interface."
version: 1.0.0
homepage: https://solrum.dev
repository: https://github.com/solrum/flutter/tree/master/text_input_formatter

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  decimal: ^3.0.2

topics:
  - formatter